apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spark-api.fullname" . }}-api
  labels:
    app: sparkapi
  {{- include "spark-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: sparkapi
    {{- include "spark-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: sparkapi
      {{- include "spark-api.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: INFLUXDB_HOST
          value: {{ .Values.env.InfluxDBHost }}
        - name: INFLUXDB_DATABASE_NAME
          value: {{ .Values.env.InfluxDBDatabase }}
        - name: PROM_REMOTE_WRITE_URL
          value: {{ .Values.env.PromRemoteWriteUrl }}
        - name: PROM_HTTP_URL
          value: {{ .Values.env.PromHttpUrl }}
        - name: DASHBOARD_URL_TEMPLATE
          value: {{ .Values.env.DashboardUrlTemplate }}
        - name: Brokers
          value: {{ .Values.env.KafkaBrokers }}
        - name: Topic
          value: {{ .Values.env.KafkaTopic }}
        - name: batchSendNum
          value: {{ .Values.env.BatchSendNum }}
        image: {{ .Values.api.sparkapi.image.repository }}:{{ .Values.api.sparkapi.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.api.sparkapi.image.imagePullPolicy }}
        name: sparkapi
        ports:
        - containerPort: 8087
          protocol: TCP
        resources: {}