apiVersion: v2
appVersion: 0.8.2-4fb1a6c
description: A Helm chart to deploy fluid in Kubernetes
home: https://github.com/fluid-cloudnative/fluid
keywords:
- category:data
- fluid
- namespace:fluid-system
- releaseName:fluid
name: fluid
type: application
version: 0.8.2
