apiVersion: v1
kind: Service
metadata:
  name: {{ include "thanos.fullname" . }}-store
  labels:
    app.kubernetes.io/component: object-store-gateway
    app.kubernetes.io/instance: thanos-store
    app.kubernetes.io/name: thanos-store    
  {{- include "thanos.labels" . | nindent 4 }}
spec:
  type: {{ .Values.store.type }}
  selector:
    app.kubernetes.io/component: object-store-gateway
    app.kubernetes.io/instance: thanos-store
    app.kubernetes.io/name: thanos-store
  ports:
	{{- .Values.store.ports | toYaml | nindent 2 -}}
