apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "thanos.fullname" . }}-receive-router
  labels:
    app.kubernetes.io/component: thanos-receive-router
  {{- include "thanos.labels" . | nindent 4 }}
