---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "thanos.fullname" . }}-store
  labels:
    app.kubernetes.io/component: object-store-gateway
  {{- include "thanos.labels" . | nindent 4 }}