apiVersion: v1
kind: Service
metadata:
  name: {{ include "thanos.fullname" . }}-receive-router
  labels:
    app.kubernetes.io/component: thanos-receive-router
    app.kubernetes.io/instance: thanos-receive
    app.kubernetes.io/name: thanos-receive    
  {{- include "thanos.labels" . | nindent 4 }}
spec:
  type: {{ .Values.receiveRouter.type }}
  selector:
    app.kubernetes.io/component: thanos-receive-router
    app.kubernetes.io/instance: thanos-receive
    app.kubernetes.io/name: thanos-receive
  ports:
	{{- .Values.receiveRouter.ports | toYaml | nindent 2 -}}