apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "thanos.fullname" . }}-receive-ingestor
  labels:
    app.kubernetes.io/component: database-write-hashring
  {{- include "thanos.labels" . | nindent 4 }}