apiVersion: v1
kind: Service
metadata:
  name: {{ include "thanos.fullname" . }}-query
  labels:
    app.kubernetes.io/component: query-layer
    app.kubernetes.io/instance: thanos-query
    app.kubernetes.io/name: thanos-query
  {{- include "thanos.labels" . | nindent 4 }}
spec:
  type: {{ .Values.query.type }}
  selector:
    app.kubernetes.io/component: query-layer
    app.kubernetes.io/instance: thanos-query
    app.kubernetes.io/name: thanos-query
  ports:
	{{- .Values.query.ports | toYaml | nindent 2 -}}
