apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "thanos.fullname" . }}-hashring-config
  labels:
  {{- include "thanos.labels" . | nindent 4 }}
data:
  hashrings.json: {{ .Values.hashringConfig.hashringsJson | quote }}