{{- if  .Values.kafkacluster.enabled }}

apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ .Release.Name }}
spec:
  kafka:
    version: {{ .Values.kafkacluster.version }}
    replicas: {{ .Values.kafkacluster.replicas.kafka }}
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: tls
      - name: external
        port: 9094
        type: {{ .Values.kafkacluster.externallistener.type }}
        tls: false        
    config:
       {{- toYaml .Values.kafkacluster.config  | nindent 6 }} 
    storage:
       {{- toYaml .Values.kafkacluster.storage.kafka  | nindent 6 }} 
    template:
      pod:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/instance
                      operator: In
                      values:
                        - {{ .Release.Name | quote }}
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - "kafka"                       
                topologyKey: "kubernetes.io/hostname"       
  zookeeper:
    replicas: {{ .Values.kafkacluster.replicas.zookeeper }}
    storage:
      {{- toYaml .Values.kafkacluster.storage.kafka  | nindent 6 }} 
    template:
      pod:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/instance
                      operator: In
                      values:
                        - {{ .Release.Name | quote }}
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - "zookeeper"                               
                topologyKey: "kubernetes.io/hostname"  
  entityOperator:
    topicOperator: {}
    userOperator: {}

{{- end }}