apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaBridge
metadata:
  name:  {{ .Values.kafkacluster.name }}-bridge
  namespace: {{ .Values.kafkacluster.namespace }}  
spec:
  replicas: 1
  bootstrapServers: {{ .Values.kafkacluster.name }}-kafka-bootstrap.{{ .Values.kafkacluster.namespace }}:9092
  http:
    port: 8080